name: securityssidabi3x
channels:
  - conda-forge
  - defaults
dependencies:
  - scapy
  - dnslib
  - aiohttp
  - aiosignal
  - async-timeout
  - attrs
  - brotlipy
  - cachetools
  - cffi
  - charset-normalizer
  - cryptography
  - frozenlist
  - google-api-core
  - google-auth
  - googleapis-common-protos
  - idna
  - influxdb
  - msgpack-python
  - multidict
  - netaddr
  - protobuf
  - pyasn1
  - pyasn1-modules
  - pycparser
  - pyopenssl
  - pysocks
  - python-dateutil
  - pytz
  - pyu2f
  - requests
  - rsa
  - six
  - typing-extensions
  - urllib3
  - yarl
  - asgiref
  - backports
  - backports.zoneinfo
  - blas
  - brotli
  - brotli-bin
  - ca-certificates
  - certifi
  - cycler
  - django
  - fonttools
  - freetype
  - giflib
  - jpeg
  - kiwisolver
  - lcms2
  - lerc
  - libbrotlicommon
  - libbrotlidec
  - libbrotlienc
  - libdeflate
  - libffi
  - libpng
  - libtiff
  - libwebp
  - libwebp-base
  - lz4-c
  - matplotlib
  - matplotlib-base
  - munkres
  - ncurses
  - numpy
  - openssl
  - packaging
  - pillow
  - pip
  - pyparsing
  - python
  - readline
  - setuptools
  - sqlite
  - sqlparse
  - tk
  - tornado
  - tzdata
  - wheel
  - xz
  - zlib
  - zstd
